default:
  ALLOWED_HOSTS: [ ]
  DATABASE_URL: ""
  DIRS_EXCLUDED:
    - .idea
    - .pytest_cache
    - .tests_artifacts
  DIRS_RESOURCES:
    - config
    - scripts
    - static
  DIRS_SOURCES:
    - src
  DIRS_TEMPLATES: [ ]
  SECRET_KEY: ""
  HOST: ""
  MODE_DEBUG: true
  MODE_PROFILING: false
  PORT: -1
  PROJECT_NAME: ""
  TEMPLATE_ENGINE: "Django"
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0


development:
  HOST: "localhost"
  PORT: 8000
  WEB_CONCURRENCY: 2
  SECRET_KEY: "1"


ci:
  HOST: "localhost"
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2


heroku:
  MODE_DEBUG: false
  HOST: "tmsfirstproj.herokuapp.com"